name: news_today
description: "Today's News project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  test: ^1.25.7
  equatable: ^2.0.5
  # uuid:
  # user_repository:
  #   path: packages/user_repository
  news_repository:
    path: packages/news_repository
  news_api:
    path: packages/news_api
  mocktail: ^1.0.4
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/placement.jpg

  fonts:
    - family: Caros
      fonts:
        - asset: fonts/CarosSoft.otf
          weight: 300
        - asset: fonts/CarosSoftMedium.otf
          weight: 500
        - asset: fonts/CarosSoftBold.otf
          weight: 600
        - asset: fonts/CarosSoftExtraBold.otf
          weight: 700
    - family: Georgia
      fonts:
        - asset: fonts/Georgia.ttf
          weight: 400
        - asset: fonts/GeorgiaItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/GeorgiaBold.ttf
          weight: 700
        - asset: fonts/GeorgiaBoldItalic.ttf
          weight: 700
